# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Cotiviti Labs Blog"
license = "MIT"
licenselink = "https://github.com/nraboy/hugo-phlat-theme/blob/master/LICENSE.md"
description = "A flat theme for the Hugo static website engine, designed exclusively for Cotiviti Labs"
homepage = "http://www.capertongillett.com"
tags = ["flat", "bootstrap", "font-awesome"]
features = ["responsive", "mobile-friendly"]
min_version = 0.14

[author]
  name = "Caperton Gillett"
  homepage = "http://www.capertongillett.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
